In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/pizza_sales.csv")

In [4]:
df.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1.0,1.0,hawaiian_m,1.0,1/1/2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2.0,2.0,classic_dlx_m,1.0,1/1/2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3.0,2.0,five_cheese_l,1.0,1/1/2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4.0,2.0,ital_supr_l,1.0,1/1/2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5.0,2.0,mexicana_m,1.0,1/1/2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza

In [6]:
df.shape

(48620, 12)

In [7]:
list(df.columns)

['pizza_id',
 'order_id',
 'pizza_name_id',
 'quantity',
 'order_date',
 'order_time',
 'unit_price',
 'total_price',
 'pizza_size',
 'pizza_category',
 'pizza_ingredients',
 'pizza_name']

In [8]:
df.dtypes

pizza_id             float64
order_id             float64
pizza_name_id         object
quantity             float64
order_date            object
order_time            object
unit_price           float64
total_price          float64
pizza_size            object
pizza_category        object
pizza_ingredients     object
pizza_name            object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  float64
 1   order_id           48620 non-null  float64
 2   pizza_name_id      48620 non-null  object
 3   quantity           48620 non-null  float64
 4   order_date         48620 non-null  object
 5   order_time         48620 non-null  object
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  object
 9   pizza_category     48620 non-null  object
 10  pizza_ingredients  48620 non-null  object
 11  pizza_name         48620 non-null  object
dtypes: float64(5), object(7)
memory usage: 4.5+ MB

In [10]:
df.isnull().sum()

pizza_id             0
order_id             0
pizza_name_id        0
quantity             0
order_date           0
order_time           0
unit_price           0
total_price          0
pizza_size           0
pizza_category       0
pizza_ingredients    0
pizza_name           0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.describe()

           pizza_id      order_id      quantity    unit_price   total_price
count  48620.000000  48620.000000  48620.000000  48620.000000  48620.000000
mean   24310.500000  10701.479761      1.019622     16.494132     16.821474
std    14035.529381   6180.119770      0.143077      3.621789      4.437398
min        1.000000      1.000000      1.000000      9.750000      9.750000
25%    12155.750000   5337.000000      1.000000     12.750000     12.750000
50%    24310.500000  10682.500000      1.000000     16.500000     16.500000
75%    36465.250000  16100.000000      1.000000     20.250000     20.500000
max    48620.000000  21350.000000      4.000000     35.950000     83.000000

In [14]:
df[["quantity", "unit_price", "total_price"]].describe()

           quantity    unit_price   total_price
count  48620.000000  48620.000000  48620.000000
mean       1.019622     16.494132     16.821474
std        0.143077      3.621789      4.437398
min        1.000000      9.750000      9.750000
25%        1.000000     12.750000     12.750000
50%        1.000000     16.500000     16.500000
75%        1.000000     20.250000     20.500000
max        4.000000     35.950000     83.000000

In [15]:
df["pizza_size"].value_counts()

pizza_size
L      18526
M      15385
S      14137
XL       544
XXL       28
Name: count, dtype: int64

In [16]:
df["pizza_category"].value_counts()

pizza_category
Classic    14579
Supreme    11777
Veggie     11449
Chicken    10815
Name: count, dtype: int64

In [17]:
df["pizza_name"].nunique()

32

In [18]:
df["pizza_name"].nunique()

32

In [19]:
df["order_id"].nunique()

21350

# Pizza Sales Analytics — Data Exploration

## Objective

The objective of this notebook is to understand, profile,
validate, and prepare the pizza sales dataset before performing
SQL analysis and building the Power BI dashboard.

## Dataset

The dataset contains pizza order transaction records with
information about orders, quantities, prices, pizza sizes,
categories, ingredients, and pizza names.

## Analysis Stages

1. Data loading
2. Dataset structure
3. Data types
4. Missing-value analysis
5. Duplicate analysis
6. Statistical analysis
7. Categorical analysis
8. Data validation
9. Data preparation

In [20]:
df["order_date"].head()

0    1/1/2015
1    1/1/2015
2    1/1/2015
3    1/1/2015
4    1/1/2015
Name: order_date, dtype: object

In [23]:
df["order_date"].head(20)

0     1/1/2015
1     1/1/2015
2     1/1/2015
3     1/1/2015
4     1/1/2015
5     1/1/2015
6     1/1/2015
7     1/1/2015
8     1/1/2015
9     1/1/2015
10    1/1/2015
11    1/1/2015
12    1/1/2015
13    1/1/2015
14    1/1/2015
15    1/1/2015
16    1/1/2015
17    1/1/2015
18    1/1/2015
19    1/1/2015
Name: order_date, dtype: object

In [24]:
df["order_date"].sample(20)

9114       8/3/2015
29465      5/8/2015
36223    26-09-2015
31047    17-08-2015
18568    16-05-2015
1488      11/1/2015
46624    14-12-2015
1483      11/1/2015
17009      6/5/2015
11020    23-03-2015
5937     13-02-2015
13266      8/4/2015
6199     15-02-2015
42865    18-11-2015
32217    26-08-2015
32024    24-08-2015
43971    26-11-2015
35509    19-09-2015
1553      12/1/2015
29841      8/8/2015
Name: order_date, dtype: object

In [25]:
import pandas as pd

def convert_date(x):
    x = str(x).strip()
    
    if "-" in x:
        return pd.to_datetime(x, format="%d-%m-%Y")
    else:
        return pd.to_datetime(x, format="%m/%d/%Y")

df["order_date"] = df["order_date"].apply(convert_date)

In [26]:
df["order_date"].head()

0   2015-01-01
1   2015-01-01
2   2015-01-01
3   2015-01-01
4   2015-01-01
Name: order_date, dtype: datetime64[ns]

In [27]:
df["order_date"].dtype

dtype('<M8[ns]')

In [28]:
df["order_date"].min(), df["order_date"].max()

(Timestamp('2015-01-01 00:00:00'), Timestamp('2015-12-31 00:00:00'))

In [29]:
df["quantity"].describe()

count    48620.000000
mean         1.019622
std          0.143077
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          4.000000
Name: quantity, dtype: float64

In [30]:
df[df["quantity"] <= 0]

Empty DataFrame
Columns: [pizza_id, order_id, pizza_name_id, quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name]
Index: []

In [31]:
(df["quantity"] <= 0).sum()

np.int64(0)

In [32]:
df[df["unit_price"] <= 0]

Empty DataFrame
Columns: [pizza_id, order_id, pizza_name_id, quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name]
Index: []

In [33]:
(df["unit_price"] <= 0).sum()

np.int64(0)

In [34]:
df[df["total_price"] <= 0]

Empty DataFrame
Columns: [pizza_id, order_id, pizza_name_id, quantity, order_date, order_time, unit_price, total_price, pizza_size, pizza_category, pizza_ingredients, pizza_name]
Index: []

In [38]:
(df["total_price"] <= 0).sum()

np.int64(0)

In [39]:
df["calculated_total"] = df["quantity"] * df["unit_price"]

df["difference"] = (
    df["total_price"] - df["calculated_total"]
)

In [40]:
df["difference"].describe()

count    48620.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: difference, dtype: float64

In [41]:
df["pizza_size"].unique()

array(['M', 'L', 'S', 'XL', 'XXL'], dtype=object)

In [42]:
df["pizza_size"].value_counts()

pizza_size
L      18526
M      15385
S      14137
XL       544
XXL       28
Name: count, dtype: int64

In [43]:
df["pizza_category"].unique()

array(['Classic', 'Veggie', 'Supreme', 'Chicken'], dtype=object)

In [44]:
df["pizza_category"].value_counts()

pizza_category
Classic    14579
Supreme    11777
Veggie     11449
Chicken    10815
Name: count, dtype: int64

In [45]:
df.isnull().sum()

pizza_id             0
order_id             0
pizza_name_id        0
quantity             0
order_date           0
order_time           0
unit_price           0
total_price          0
pizza_size           0
pizza_category       0
pizza_ingredients    0
pizza_name           0
calculated_total     0
difference           0
dtype: int64

In [46]:
df.duplicated().sum()

np.int64(0)

In [47]:
df["order_id"].duplicated().sum()

np.int64(27270)

In [48]:
df["order_id"].nunique()

21350

In [49]:
df["order_id"].nunique()

21350

In [50]:
df["year"] = df["order_date"].dt.year
df["month_number"] = df["order_date"].dt.month
df["month_name"] = df["order_date"].dt.month_name()
df["day_name"] = df["order_date"].dt.day_name()

In [51]:
df["order_time"].head()

0    11:38:36
1    11:57:40
2    11:57:40
3    11:57:40
4    11:57:40
Name: order_time, dtype: object

In [52]:
df["order_time"] = pd.to_datetime(
    df["order_time"],
    format="%H:%M:%S"
)

In [53]:
df["order_hour"] = df["order_time"].dt.hour

In [54]:
df[
    [
        "order_date",
        "year",
        "month_number",
        "month_name",
        "day_name",
        "order_time",
        "order_hour"
    ]
].head(10)

,order_date,year,month_number,month_name,day_name,order_time,order_hour
0,2015-01-01,2015,1,January,Thursday,1900-01-01 11:38:36,11
1,2015-01-01,2015,1,January,Thursday,1900-01-01 11:57:40,11
2,2015-01-01,2015,1,January,Thursday,1900-01-01 11:57:40,11
3,2015-01-01,2015,1,January,Thursday,1900-01-01 11:57:40,11
4,2015-01-01,2015,1,January,Thursday,1900-01-01 11:57:40,11
5,2015-01-01,2015,1,January,Thursday,1900-01-01 11:57:40,11
6,2015-01-01,2015,1,January,Thursday,1900-01-01 12:12:28,12
7,2015-01-01,2015,1,January,Thursday,1900-01-01 12:12:28,12
8,2015-01-01,2015,1,January,Thursday,1900-01-01 12:16:31,12
9,2015-01-01,2015,1,January,Thursday,1900-01-01 12:21:30,12

In [55]:
df.drop(
    columns=["calculated_total", "difference"],
    inplace=True
)

In [57]:
df.columns

Index(['pizza_id', 'order_id', 'pizza_name_id', 'quantity', 'order_date',
       'order_time', 'unit_price', 'total_price', 'pizza_size',
       'pizza_category', 'pizza_ingredients', 'pizza_name', 'year',
       'month_number', 'month_name', 'day_name', 'order_hour'],
      dtype='object')

In [58]:
df.shape

(48620, 17)

In [59]:
df.info

<bound method DataFrame.info of        pizza_id  order_id  pizza_name_id  quantity order_date  \
0           1.0       1.0     hawaiian_m       1.0 2015-01-01
1           2.0       2.0  classic_dlx_m       1.0 2015-01-01
2           3.0       2.0  five_cheese_l       1.0 2015-01-01
3           4.0       2.0    ital_supr_l       1.0 2015-01-01
4           5.0       2.0     mexicana_m       1.0 2015-01-01
...         ...       ...            ...       ...        ...
48615   48616.0   21348.0  ckn_alfredo_m       1.0 2015-12-31
48616   48617.0   21348.0  four_cheese_l       1.0 2015-12-31
48617   48618.0   21348.0   napolitana_s       1.0 2015-12-31
48618   48619.0   21349.0     mexicana_l       1.0 2015-12-31
48619   48620.0   21350.0      bbq_ckn_s       1.0 2015-12-31

               order_time  unit_price  total_price pizza_size pizza_category  \
0     1900-01-01 11:38:36       13.25        13.25          M        Classic
1     1900-01-01 11:57:40       16.00        16.00          M        Classic
2     1900-01-01 11:57:40       18.50        18.50          L         Veggie
3     1900-01-01 11:57:40       20.75        20.75          L        Supreme
4     1900-01-01 11:57:40       16.00        16.00          M         Veggie
...                   ...         ...          ...        ...            ...
48615 1900-01-01 21:23:10       16.75        16.75          M        Chicken
48616 1900-01-01 21:23:10       17.95        17.95          L         Veggie
48617 1900-01-01 21:23:10       12.00        12.00          S        Classic
48618 1900-01-01 22:09:54       20.25        20.25          L         Veggie
48619 1900-01-01 23:02:05       12.75        12.75          S        Chicken

                                       pizza_ingredients  \
0               Sliced Ham, Pineapple, Mozzarella Cheese
1      Pepperoni, Mushrooms, Red Onions, Red Peppers,...
2      Mozzarella Cheese, Provolone Cheese, Smoked Go...
3      Calabrese Salami, Capocollo, Tomatoes, Red Oni...
4      Tomatoes, Red Peppers, Jalapeno Peppers, Red O...
...                                                  ...
48615  Chicken, Red Onions, Red Peppers, Mushrooms, A...
48616  Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...
48617  Tomatoes, Anchovies, Green Olives, Red Onions,...
48618  Tomatoes, Red Peppers, Jalapeno Peppers, Red O...
48619  Barbecued Chicken, Red Peppers, Green Peppers,...

                       pizza_name  year  month_number month_name  day_name  \
0              The Hawaiian Pizza  2015             1    January  Thursday
1        The Classic Deluxe Pizza  2015             1    January  Thursday
2           The Five Cheese Pizza  2015             1    January  Thursday
3       The Italian Supreme Pizza  2015             1    January  Thursday
4              The Mexicana Pizza  2015             1    January  Thursday
...                           ...   ...           ...        ...       ...
48615   The Chicken Alfredo Pizza  2015            12   December  Thursday
48616       The Four Cheese Pizza  2015            12   December  Thursday
48617        The Napolitana Pizza  2015            12   December  Thursday
48618          The Mexicana Pizza  2015            12   December  Thursday
48619  The Barbecue Chicken Pizza  2015            12   December  Thursday

       order_hour
0              11
1              11
2              11
3              11
4              11
...           ...
48615          21
48616          21
48617          21
48618          22
48619          23

[48620 rows x 17 columns]>

In [60]:
df.to_csv(
    "../data/pizza_sales_cleaned.csv",
    index=False
)

In [61]:
import os

os.path.exists("../data/pizza_sales_cleaned.csv")

True